### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by Galiwyx** [LycheeOrg/Lychee-Docker#71] opened 2020-07-03 20:46 UTC
Hello,

I'm trying to deploy a Lychee image on docker. Im' a relative beginner.  In logs I have an error:
![image](https://user-images.githubusercontent.com/206181/86496681-c2cd8800-bd7e-11ea-8e72-621b20d54571.png)
I think it's related with the databse. However, I set same password for mysql_password and db_password. Am I missed something ? 
This is my docker-compose file:

`version: '3'

services:
  lychee_db:
    container_name: lychee_db
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=loremtest
      - MYSQL_DATABASE=lychee
      - MYSQL_USER=lychee
      - MYSQL_PASSWORD=lorem
    expose: 
      - 3306
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - lychee
    restart: unless-stopped

  lychee:
    image: lycheeorg/lychee
    container_name: lychee
    ports:
      - 90:80
    volumes:
      - /srv/dev-disk-by-label-AppData/AppData/Config/Lychee:/conf
      - /srv/dev-disk-by-label-Files/Files/Medias/Uploads:/uploads
      - /srv/dev-disk-by-label-Files/Files/Medias/Sym:/sym
    networks:
      - lychee
    environment:
      - PUID=1000
      - PGID=100
      # PHP timezone e.g. PHP_TZ=America/New_York
      - PHP_TZ=Europe/Paris
      #- APP_NAME=Laravel
      #- APP_ENV=local
      #- APP_DEBUG=true
      #- APP_URL=http://localhost
      #- LOG_CHANNEL=stack
      - DB_CONNECTION=mysql
      - DB_HOST=lychee_db
      - DB_PORT=3306
      - DB_DATABASE=lychee
      - DB_USERNAME=lychee
      - DB_PASSWORD=lorem
      #- DB_DROP_CLEAR_TABLES_ON_ROLLBACK=false
      #- DB_OLD_LYCHEE_PREFIX=''
      #- BROADCAST_DRIVER=log
      #- CACHE_DRIVER=file
      #- SESSION_DRIVER=file
      #- SESSION_LIFETIME=120
      #- QUEUE_DRIVER=sync
      #- SECURITY_HEADER_HSTS_ENABLE=false
      #- REDIS_HOST=127.0.0.1
      #- REDIS_PASSWORD=null
      #- REDIS_PORT=6379
      #- MAIL_DRIVER=smtp
      #- MAIL_HOST=smtp.mailtrap.io
      #- MAIL_PORT=2525
      #- MAIL_USERNAME=null
      #- MAIL_PASSWORD=null
      #- MAIL_ENCRYPTION=null
      #- PUSHER_APP_ID=''
      #- PUSHER_APP_KEY=''
      #- PUSHER_APP_SECRET=''
      #- PUSHER_APP_CLUSTER=mt1
      - STARTUP_DELAY=30
    restart: unless-stopped
    depends_on:
      - lychee_db

networks:
  lychee:

volumes:
  mysql:`

Thank you!!

**Comment by lord-carlos** [comment] 2020-07-04 13:30
I have the same problem.

**Comment by d7415** [comment] 2020-07-04 13:44
docker-compose isn't my area. Those errors do look like a problem with the SQL server. It might not be ready (though I'd expect a "Connection refused" in that case). Try increasing `STARTUP_DELAY`.

If that doesn't work, it may be worth opening a shell (or just a mysql command) on the lychee container to if you can connect to the mysql container manually. Another option would be to try using sqlite.

**Comment by lord-carlos** [comment] 2020-07-04 13:57
`SQLSTATE[HY000] [1045] Access denied for user 'lychee'@'172.20.0.2'`
For me this IP address is lychee, and lychee_db would be .3

```
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' lychee_db
172.20.0.3
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' lychee
172.20.0.2
```

**Comment by d7415** [comment] 2020-07-04 14:03
Without thinking too hard about it I think that part's correct - The access control is based on source IP.

**Comment by lord-carlos** [comment] 2020-07-04 14:30
```
curl 172.20.0.3:3306 --output foo.txt
5.5.5-10.5.4-MariaDB-1:10.5.4+maria~focall%6#J+9{!-0lQ0;vdo#\&Imysql_native_password!#08S01Got packets out of order
```
Network works.
```
mariadb -u lychee -h 172.20.0.3 -p
Enter password:
ERROR 1045 (28000): Access denied for user 'lychee'@'172.20.0.2' (using password: YES)
```
Password does not. 🤔

**Comment by Galiwyx** [comment] 2020-07-05 11:12
> 
> 
> docker-compose isn't my area. Those errors do look like a problem with the SQL server. It might not be ready (though I'd expect a "Connection refused" in that case). Try increasing `STARTUP_DELAY`.
> 
> If that doesn't work, it may be worth opening a shell (or just a mysql command) on the lychee container to if you can connect to the mysql container manually. Another option would be to try using sqlite.

Hello d4715,

Thanks for your reply, I added a delay of 30 seconds but unfortunately the problem is still here.

**Comment by d7415** [comment] 2020-07-05 12:01
> Thanks for your reply, I added a delay of 30 seconds but unfortunately the problem is still here.

There was already a 30 second delay, but yes as @lord-carlos discovered the problem seems to be with the database container credentials.

If I get a change to look further I will - I already checked the docs to make sure the variables used are still valid. Otherwise lord-carlos might come up with something.

**Comment by lord-carlos** [comment] 2020-07-05 12:26
I messed around a bit with just mariaDB docker (without docker-compose) and could connect from another mariadb client. That is how far I have come. Not sure yet why mariadb does not accept the password when starting through compose.
Will do some more testing later. Might be in a few hours, might be in a few days.

**Comment by Galiwyx** [comment] 2020-07-05 12:31
Hello thank you, d715 and lord-carlos. I'll waiting your feedbacks.

**Comment by lord-carlos** [comment] 2020-07-28 18:47
Ok, fixed it for me. 
Probably **not a lychee** or mysql **bug**.
Had something to do with the volume. Maybe I started the db with another pw fist?
```
docker-compose stop lychee_db
docker-compose stop lychee
docker-compose rm lychee_db
```
Then I changed the volume from `- mysql:/var/lib/mysql` to `- ./lyche_db:/var/lib/mysql`
```
docker-compose up -d --no-deps;
```
That fixed it. 

What even does this do?
```yaml
...
    volumes:
    - mysql:/var/lib/mysq
...
volumes:
 mysql:
```
Where is the data? What advantage does it have over saving it in the current dir?

**Comment by d7415** [comment] 2020-07-28 21:37
> Where is the data? What advantage does it have over saving it in the current dir?

As I understand it, in Docker's own storage, as a named volume. This is an example file, and should be adjusted to suit your needs - if you'd prefer a local file, that's an option. If you need a more detailed answer, it's probably worth reading up on Docker Compose, but that's out of scope here.

**Comment by d7415** [comment] 2020-07-29 13:08
Finally got around to starting a VM for this. Other than extending the startup delay, the file works as-is, so I was unable to reproduce. I'm closing this issue.

**Closed by d7415** 2020-07-29 13:08 UTC
